"use client";
import {ReactNode,useEffect,useState} from "react";

export function ClientExperience({children}:{children:ReactNode}){
 const [firstLogin,setFirstLogin]=useState(false);const [accepted,setAccepted]=useState(false);const [panel,setPanel]=useState("");
 useEffect(()=>{setFirstLogin(!localStorage.getItem("velora-client-terms-v1"))},[]);
 const agree=()=>{localStorage.setItem("velora-client-terms-v1",new Date().toISOString());setFirstLogin(false)};
 return <>{children}<div className="client-floating-tabs"><button onClick={()=>setPanel("terms")}>Contracts & terms</button><button onClick={()=>setPanel("privacy")}>Privacy & security</button></div>
 {firstLogin&&<div className="terms-gate"><section><small>WELCOME TO YOUR VELORA PORTAL</small><h1>One quick thing<br/><i>before we create.</i></h1><p>Please review and accept the client services terms. Your projects, invoices and files will unlock after acceptance.</p><div className="terms-scroll"><h2>Client Services Agreement</h2><p><b>1. Services.</b> Velora Vista Visuals Ltd. will provide the services and deliverables listed in your selected or custom plan.</p><p><b>2. Payment.</b> Recurring plans are billed on the date shown in your portal. Project work follows the approved invoice schedule.</p><p><b>3. Scheduling.</b> Production dates are confirmed in writing. Rescheduling with less than 48 hours’ notice may require a new production fee.</p><p><b>4. Revisions.</b> Included revision rounds are defined by your plan. Additional work is quoted before it begins.</p><p><b>5. Usage and releases.</b> Final usage rights begin after full payment. Required property, location, music and talent permissions must be approved before release.</p><p><b>6. Storage.</b> Final files remain available through linked delivery folders for the period stated in your project details.</p><p><b>7. Cancellation.</b> Plan changes or cancellations must be requested by calling 778-820-0485 and remain subject to the signed service agreement.</p><p><b>8. Privacy.</b> Account information is used to deliver services, process payments, send project updates and maintain business records.</p></div><label className="terms-check"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/><span>I have read and agree to the Client Services Agreement, Privacy Notice and electronic signature policy.</span></label><button className="terms-accept" disabled={!accepted} onClick={agree}>Accept & enter my portal ↗</button><a href="mailto:info@veloravistavisuals.com?subject=Question%20about%20client%20terms">I have a question before agreeing</a></section></div>}
 {panel&&<div className="client-info-modal"><section><button onClick={()=>setPanel("")}>Close ×</button><small>CLIENT DOCUMENT CENTRE</small><h2>{panel==="terms"?"Contracts & terms":"Privacy & security"}</h2>{panel==="terms"?<><article><div><b>Monthly Content Services Agreement</b><span className="paid">● Signed July 28, 2026</span></div><p>Momentum plan · Effective August 1, 2026</p><button>View signed copy ↗</button></article><article><div><b>Property & Location Release</b><span>Not required</span></div><p>Current projects use client-owned locations.</p></article><article><div><b>Terms acceptance history</b><span className="paid">● Current</span></div><p>Latest terms version accepted on this account.</p></article></>:<><div className="privacy-list"><label><span><b>Login alerts</b><small>Email me when a new device signs in</small></span><input type="checkbox" defaultChecked/></label><label><span><b>Invoice notifications</b><small>Payment receipts and billing reminders</small></span><input type="checkbox" defaultChecked/></label><label><span><b>Project notifications</b><small>Approvals, revisions and delivery updates</small></span><input type="checkbox" defaultChecked/></label><label><span><b>Marketing updates</b><small>Occasional studio news and offers</small></span><input type="checkbox"/></label></div><article><b>Account security</b><p>Password last changed 24 days ago · One active session</p><button>Request password reset ↗</button></article><article><b>Your data</b><p>Request a copy or correction of personal information connected to this account.</p><a href="mailto:info@veloravistavisuals.com?subject=Client%20data%20request">Contact privacy team ↗</a></article></>}</section></div>}
 </>
}
